-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 12:48:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET latin1 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`City` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL COMMENT 'Название города',
  `link` VARCHAR(300) NOT NULL COMMENT 'Ссылка на сайте погоды, где можно найти проноз на данный город',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Таблица городов и ссылок на них на сайте погоды';


-- -----------------------------------------------------
-- Table `weather`.`ForecastOnDay`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`ForecastOnDay` (
  `id` INT(11) NOT NULL,
  `date` DATE NOT NULL,
  `city` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_city_forecast_idx` (`city` ASC) VISIBLE,
  CONSTRAINT `FK_city_forecast`
    FOREIGN KEY (`city`)
    REFERENCES `weather`.`City` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weather`.`Weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`Weather` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `partOfDay` VARCHAR(45) NOT NULL COMMENT 'Часть дня(утро, день, вечер, ночь)',
  `temperature` TINYINT NOT NULL COMMENT 'температура в градусах Цельсия',
  `wind` TINYINT NOT NULL COMMENT 'направление ветра\n',
  `speed` TINYINT NOT NULL DEFAULT 0 COMMENT 'Скорость ветра\n',
  `humidity` TINYINT NOT NULL DEFAULT 0 COMMENT 'влажность воздуха в процентах',
  `rainfall` FLOAT NOT NULL DEFAULT 0 COMMENT 'осадки в милиметрах',
  `sky` VARCHAR(45) NOT NULL COMMENT 'Состояние неба: пасмурно, облачно, ясно, переменная облачность, облачно с прояснениями, небольшой дождь, сильный дождь, гроза',
  `forecastOnDay` INT(11) NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_forecast_weather_idx` (`forecastOnDay` ASC) VISIBLE,
  CONSTRAINT `FK_forecast_weather`
    FOREIGN KEY (`forecastOnDay`)
    REFERENCES `weather`.`ForecastOnDay` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'Admin' IDENTIFIED BY '242526';

GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `weather`.* TO 'Admin';
GRANT SELECT ON TABLE `weather`.* TO 'Admin';
GRANT ALL ON `weather`.* TO 'Admin';
GRANT EXECUTE ON ROUTINE `weather`.* TO 'Admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `weather`.* TO 'Admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
