-- MySQL Script generated by MySQL Workbench
-- Thu Oct  8 18:59:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET latin1 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`citys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`citys` (
  `CityId` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL COMMENT 'Название города',
  `Link` VARCHAR(300) NOT NULL COMMENT 'Ссылка на сайте погоды, где можно найти проноз на данный город',
  PRIMARY KEY (`CityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Таблица городов и ссылок на них на сайте погоды';


-- -----------------------------------------------------
-- Table `weather`.`weatherforecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`weatherforecasts` (
  `WeatherId` INT NOT NULL AUTO_INCREMENT,
  `Speed` TINYINT NOT NULL DEFAULT 0 COMMENT 'Скорость ветра\n',
  `Wind` VARCHAR(45) NOT NULL,
  `Temperature` TINYINT NOT NULL COMMENT 'температура в градусах Цельсия',
  `Date` DATETIME NOT NULL,
  `PartOfDay` VARCHAR(45) NOT NULL COMMENT 'Часть дня(утро, день, вечер, ночь)',
  `Humidity` TINYINT NOT NULL DEFAULT 0 COMMENT 'влажность воздуха в процентах',
  `Precipitation` INT NOT NULL DEFAULT 0 COMMENT 'вероятность осадков',
  `Sky` VARCHAR(45) NOT NULL COMMENT 'Состояние неба: пасмурно, облачно, ясно, переменная облачность, облачно с прояснениями, небольшой дождь, сильный дождь, гроза',
  `Preassure` INT NOT NULL,
  `CityId` INT(11) NOT NULL,
  PRIMARY KEY (`WeatherId`),
  INDEX `fk_weatherhour_city_idx` (`CityId` ASC) INVISIBLE,
  CONSTRAINT `fk_weatherhour_city`
    FOREIGN KEY (`CityId`)
    REFERENCES `weather`.`citys` (`CityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
