-- MySQL Script generated by MySQL Workbench
-- Fri Oct  9 21:20:33 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weather
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weather` DEFAULT CHARACTER SET utf8mb4 ;
USE `weather` ;

-- -----------------------------------------------------
-- Table `weather`.`citys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`citys` (
  `CityId` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Название города',
  PRIMARY KEY (`CityId`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COMMENT = 'Таблица городов и ссылок на них на сайте погоды';


-- -----------------------------------------------------
-- Table `weather`.`weatherforecasts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `weather`.`weatherforecasts` (
  `WeatherId` INT(11) NOT NULL AUTO_INCREMENT,
  `Speed` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'Скорость ветра\\n',
  `Wind` CHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `Temperature` TINYINT(4) NOT NULL COMMENT 'температура в градусах Цельсия',
  `Date` DATETIME NOT NULL,
  `PartOfDay` CHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Часть дня(утро, день, вечер, ночь)',
  `Humidity` TINYINT(4) NOT NULL DEFAULT '0' COMMENT 'влажность воздуха в процентах',
  `Precipitation` INT(11) NOT NULL DEFAULT '0' COMMENT 'вероятность осадков',
  `Sky` CHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Состояние неба: пасмурно, облачно, ясно, переменная облачность, облачно с прояснениями, небольшой дождь, сильный дождь, гроза',
  `Pressure` INT(11) NOT NULL,
  `CityId` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`WeatherId`),
  INDEX `fk_weatherhour_city_idx` (`CityId` ASC) VISIBLE,
  CONSTRAINT `fk_weatherhour_city`
    FOREIGN KEY (`CityId`)
    REFERENCES `weather`.`citys` (`CityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5601
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
